{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "steadystack.fullname" . }}-web
  namespace: {{ default .Release.Namespace .Values.metrics.serviceMonitor.namespace }}
  labels:
    {{- include "steadystack.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "steadystack.web.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /api/health
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      {{- with .Values.metrics.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
{{- end }}
