export default {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "header-max-length": [2, "always", 100],
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "chore",
        "docs",
        "refactor",
        "perf",
        "test",
        "build",
        "ci",
        "style",
        "revert",
      ],
    ],
    "scope-enum": [
      2,
      "always",
      [
        "web",
        "worker",
        "cli",
        "native",
        "probe",
        "e2e",
        "api",
        "auth",
        "core",
        "db",
        "email",
        "env",
        "types",
        "shared",
        "config",
        "infra",
        "wasm-parser",
        "github-action",
        "terraform-provider",
        "deps",
        "release",
      ],
    ],
  },
};
